<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dataset
[
   <!ELEMENT dataset (header,body)>
   <!ATTLIST dataset name CDATA #REQUIRED>
   <!ATTLIST dataset version CDATA "3.7.3">

   <!ELEMENT header (notes?,attributes)>
   <!ELEMENT body (instances)>
   <!ELEMENT notes ANY>   <!--  comments, information, copyright, etc. -->

   <!ELEMENT attributes (attribute+)>
   <!ELEMENT attribute (labels?,metadata?,attributes?)>
   <!ATTLIST attribute name CDATA #REQUIRED>
   <!ATTLIST attribute type (numeric|date|nominal|string|relational) #REQUIRED>
   <!ATTLIST attribute format CDATA #IMPLIED>
   <!ATTLIST attribute class (yes|no) "no">
   <!ELEMENT labels (label*)>   <!-- only for type "nominal" -->
   <!ELEMENT label ANY>
   <!ELEMENT metadata (property*)>
   <!ELEMENT property ANY>
   <!ATTLIST property name CDATA #REQUIRED>

   <!ELEMENT instances (instance*)>
   <!ELEMENT instance (value*)>
   <!ATTLIST instance type (normal|sparse) "normal">
   <!ATTLIST instance weight CDATA #IMPLIED>
   <!ELEMENT value (#PCDATA|instances)*>
   <!ATTLIST value index CDATA #IMPLIED>   <!-- 1-based index (only used for instance format "sparse") -->
   <!ATTLIST value missing (yes|no) "no">
]
>

<dataset name="time_interval" version="3.7.3">
   <header>
      <attributes>
         <attribute format="yyyy-MM-dd&apos;T&apos;HH:mm:ss:SSS" name="from" type="date"/>
         <attribute format="yyyy-MM-dd&apos;T&apos;HH:mm:ss:SSS" name="to" type="date"/>
         <attribute name="class" type="nominal">
            <labels>
               <label>Joggen</label>
               <label>Skaten</label>
               <label>spazieren</label>
               <label>biken</label>
               <label>crosstrainer</label>
            </labels>
         </attribute>
      </attributes>
   </header>
   <body>
      <instances>
         <instance>
            <value>2010-05-25T21:52:05:320</value>
            <value>2010-05-25T21:52:08:480</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T21:52:08:520</value>
            <value>2010-05-25T21:52:11:680</value>
            <value>Skaten</value>
         </instance>
         <instance>
            <value>2010-05-25T21:52:11:720</value>
            <value>2010-05-25T21:52:21:360</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T21:52:21:400</value>
            <value>2010-05-25T21:52:24:560</value>
            <value>Skaten</value>
         </instance>
         <instance>
            <value>2010-05-25T21:52:24:600</value>
            <value>2010-05-25T21:52:25:520</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T21:52:25:600</value>
            <value>2010-05-25T21:52:28:760</value>
            <value>Skaten</value>
         </instance>
         <instance>
            <value>2010-05-25T21:52:28:800</value>
            <value>2010-05-25T21:52:44:840</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T21:52:44:880</value>
            <value>2010-05-25T21:52:57:720</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T21:52:57:760</value>
            <value>2010-05-25T21:53:00:960</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T21:53:01:000</value>
            <value>2010-05-25T21:53:07:400</value>
            <value>Skaten</value>
         </instance>
         <instance>
            <value>2010-05-25T21:53:07:440</value>
            <value>2010-05-25T21:53:10:600</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T21:53:10:640</value>
            <value>2010-05-25T21:53:20:280</value>
            <value>Skaten</value>
         </instance>
         <instance>
            <value>2010-05-25T21:53:20:320</value>
            <value>2010-05-25T21:53:21:600</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T21:53:21:640</value>
            <value>2010-05-25T21:53:29:560</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T21:53:29:600</value>
            <value>2010-05-25T21:53:32:760</value>
            <value>Skaten</value>
         </instance>
         <instance>
            <value>2010-05-25T21:53:32:800</value>
            <value>2010-05-25T21:53:42:200</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T21:53:42:240</value>
            <value>2010-05-25T21:53:47:280</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T21:53:47:320</value>
            <value>2010-05-25T21:53:56:920</value>
            <value>Skaten</value>
         </instance>
         <instance>
            <value>2010-05-25T21:53:56:960</value>
            <value>2010-05-25T21:54:00:120</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T21:54:00:160</value>
            <value>2010-05-25T21:54:13:000</value>
            <value>Skaten</value>
         </instance>
         <instance>
            <value>2010-05-25T21:54:13:040</value>
            <value>2010-05-25T21:54:14:160</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T21:54:14:200</value>
            <value>2010-05-25T21:54:19:200</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T21:54:19:240</value>
            <value>2010-05-25T21:54:19:280</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T21:54:19:320</value>
            <value>2010-05-25T21:54:24:200</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T21:54:24:240</value>
            <value>2010-05-25T21:54:27:360</value>
            <value>Skaten</value>
         </instance>
         <instance>
            <value>2010-05-25T21:54:27:400</value>
            <value>2010-05-25T21:54:42:000</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T21:54:42:040</value>
            <value>2010-05-25T21:54:45:120</value>
            <value>Skaten</value>
         </instance>
         <instance>
            <value>2010-05-25T21:54:45:160</value>
            <value>2010-05-25T21:55:11:680</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T21:55:11:720</value>
            <value>2010-05-25T21:55:14:840</value>
            <value>Skaten</value>
         </instance>
         <instance>
            <value>2010-05-25T21:55:14:880</value>
            <value>2010-05-25T21:55:29:560</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T21:55:29:600</value>
            <value>2010-05-25T21:55:32:760</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T21:55:32:800</value>
            <value>2010-05-25T21:55:33:280</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T21:55:33:320</value>
            <value>2010-05-25T21:57:49:760</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T21:57:49:800</value>
            <value>2010-05-25T21:57:50:200</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T21:57:50:240</value>
            <value>2010-05-25T21:58:11:560</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T21:58:11:600</value>
            <value>2010-05-25T21:58:16:360</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T21:58:16:400</value>
            <value>2010-05-25T21:58:56:160</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T21:58:56:200</value>
            <value>2010-05-25T21:58:56:480</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T21:58:56:520</value>
            <value>2010-05-25T21:59:23:520</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T21:59:23:560</value>
            <value>2010-05-25T21:59:23:680</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T21:59:23:720</value>
            <value>2010-05-25T22:00:04:880</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:00:04:920</value>
            <value>2010-05-25T22:00:05:320</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:00:05:360</value>
            <value>2010-05-25T22:00:42:440</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:00:42:480</value>
            <value>2010-05-25T22:00:45:640</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T22:00:45:680</value>
            <value>2010-05-25T22:02:42:400</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:02:42:440</value>
            <value>2010-05-25T22:02:42:560</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:02:42:600</value>
            <value>2010-05-25T22:04:20:560</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:04:20:600</value>
            <value>2010-05-25T22:04:20:960</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:04:21:000</value>
            <value>2010-05-25T22:04:42:800</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:04:42:840</value>
            <value>2010-05-25T22:04:43:440</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:04:43:480</value>
            <value>2010-05-25T22:04:51:400</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:04:51:440</value>
            <value>2010-05-25T22:04:51:680</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:04:51:720</value>
            <value>2010-05-25T22:05:21:680</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:05:21:720</value>
            <value>2010-05-25T22:05:22:200</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:05:22:240</value>
            <value>2010-05-25T22:06:05:120</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:06:05:160</value>
            <value>2010-05-25T22:06:05:520</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:06:05:560</value>
            <value>2010-05-25T22:07:27:200</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:07:27:240</value>
            <value>2010-05-25T22:07:27:480</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:07:27:520</value>
            <value>2010-05-25T22:09:12:920</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:09:12:960</value>
            <value>2010-05-25T22:09:13:440</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:09:13:480</value>
            <value>2010-05-25T22:10:40:480</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:10:40:520</value>
            <value>2010-05-25T22:10:40:800</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:10:40:840</value>
            <value>2010-05-25T22:11:11:040</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:11:11:080</value>
            <value>2010-05-25T22:11:13:440</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T22:11:13:480</value>
            <value>2010-05-25T22:14:50:240</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:14:50:280</value>
            <value>2010-05-25T22:14:50:760</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:14:50:840</value>
            <value>2010-05-25T22:15:13:160</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:15:13:200</value>
            <value>2010-05-25T22:15:13:560</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:15:13:600</value>
            <value>2010-05-25T22:15:47:680</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:15:47:720</value>
            <value>2010-05-25T22:15:48:200</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:15:48:240</value>
            <value>2010-05-25T22:16:11:480</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:16:11:520</value>
            <value>2010-05-25T22:16:12:040</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:16:12:080</value>
            <value>2010-05-25T22:17:22:680</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:17:22:720</value>
            <value>2010-05-25T22:17:23:080</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:17:23:120</value>
            <value>2010-05-25T22:18:14:360</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:18:14:400</value>
            <value>2010-05-25T22:18:14:640</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:18:14:680</value>
            <value>2010-05-25T22:18:36:840</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:18:36:880</value>
            <value>2010-05-25T22:18:37:120</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:18:37:160</value>
            <value>2010-05-25T22:19:26:680</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:19:26:720</value>
            <value>2010-05-25T22:19:27:200</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:19:27:240</value>
            <value>2010-05-25T22:19:55:320</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:19:55:360</value>
            <value>2010-05-25T22:19:55:720</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:19:55:760</value>
            <value>2010-05-25T22:20:31:600</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:20:31:640</value>
            <value>2010-05-25T22:20:32:800</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:20:32:840</value>
            <value>2010-05-25T22:21:07:800</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:21:07:840</value>
            <value>2010-05-25T22:21:08:480</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:21:08:520</value>
            <value>2010-05-25T22:21:16:560</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:21:16:600</value>
            <value>2010-05-25T22:21:16:960</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:21:17:000</value>
            <value>2010-05-25T22:23:57:520</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:23:57:560</value>
            <value>2010-05-25T22:23:58:200</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:23:58:240</value>
            <value>2010-05-25T22:24:18:160</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:24:18:200</value>
            <value>2010-05-25T22:24:18:560</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:24:18:600</value>
            <value>2010-05-25T22:26:58:840</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:26:58:880</value>
            <value>2010-05-25T22:26:59:240</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:26:59:280</value>
            <value>2010-05-25T22:27:45:400</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:27:45:440</value>
            <value>2010-05-25T22:27:45:920</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:27:45:960</value>
            <value>2010-05-25T22:29:02:760</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:29:02:800</value>
            <value>2010-05-25T22:29:03:720</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:29:03:760</value>
            <value>2010-05-25T22:29:18:920</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:29:18:960</value>
            <value>2010-05-25T22:29:19:200</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:29:19:240</value>
            <value>2010-05-25T22:29:45:920</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:29:45:960</value>
            <value>2010-05-25T22:29:46:320</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:29:46:360</value>
            <value>2010-05-25T22:30:13:760</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:30:13:800</value>
            <value>2010-05-25T22:30:14:280</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:30:14:320</value>
            <value>2010-05-25T22:32:08:960</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:32:09:000</value>
            <value>2010-05-25T22:32:09:360</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:32:09:400</value>
            <value>2010-05-25T22:32:21:040</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:32:21:080</value>
            <value>2010-05-25T22:32:21:320</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:32:21:360</value>
            <value>2010-05-25T22:32:29:360</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:32:29:400</value>
            <value>2010-05-25T22:32:29:640</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:32:29:680</value>
            <value>2010-05-25T22:32:37:520</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:32:37:560</value>
            <value>2010-05-25T22:32:37:920</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:32:37:960</value>
            <value>2010-05-25T22:33:53:560</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:33:53:600</value>
            <value>2010-05-25T22:33:53:960</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:33:54:000</value>
            <value>2010-05-25T22:34:46:800</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:34:46:840</value>
            <value>2010-05-25T22:34:47:520</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:34:47:560</value>
            <value>2010-05-25T22:35:20:760</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:35:20:800</value>
            <value>2010-05-25T22:35:21:200</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:35:21:240</value>
            <value>2010-05-25T22:35:44:560</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:35:44:600</value>
            <value>2010-05-25T22:35:44:960</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:35:45:000</value>
            <value>2010-05-25T22:37:17:680</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:37:17:720</value>
            <value>2010-05-25T22:37:20:880</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T22:37:20:920</value>
            <value>2010-05-25T22:38:02:040</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:38:02:080</value>
            <value>2010-05-25T22:38:05:280</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T22:38:05:320</value>
            <value>2010-05-25T22:38:24:600</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:38:24:640</value>
            <value>2010-05-25T22:38:27:800</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T22:38:27:840</value>
            <value>2010-05-25T22:38:28:840</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:38:28:880</value>
            <value>2010-05-25T22:38:37:040</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:38:37:080</value>
            <value>2010-05-25T22:38:43:480</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T22:38:43:520</value>
            <value>2010-05-25T22:39:02:800</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:39:02:840</value>
            <value>2010-05-25T22:39:04:160</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:39:04:240</value>
            <value>2010-05-25T22:39:13:840</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:39:13:880</value>
            <value>2010-05-25T22:39:14:960</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:39:15:000</value>
            <value>2010-05-25T22:39:36:680</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T22:39:36:720</value>
            <value>2010-05-25T22:40:44:280</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T22:40:44:320</value>
            <value>2010-05-25T22:40:45:560</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:40:45:640</value>
            <value>2010-05-25T22:53:21:400</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T22:53:21:440</value>
            <value>2010-05-25T22:53:22:680</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T22:53:22:760</value>
            <value>2010-05-25T23:12:38:000</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T23:12:38:040</value>
            <value>2010-05-25T23:12:38:520</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T23:12:38:560</value>
            <value>2010-05-25T23:20:44:200</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T23:20:44:240</value>
            <value>2010-05-25T23:20:45:360</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T23:20:45:440</value>
            <value>2010-05-25T23:32:20:680</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T23:32:20:720</value>
            <value>2010-05-25T23:32:21:640</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T23:32:21:720</value>
            <value>2010-05-25T23:35:43:800</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T23:35:43:840</value>
            <value>2010-05-25T23:35:44:440</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T23:35:44:520</value>
            <value>2010-05-25T23:43:11:920</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T23:43:11:960</value>
            <value>2010-05-25T23:43:12:360</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T23:43:12:400</value>
            <value>2010-05-25T23:43:17:840</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T23:43:17:880</value>
            <value>2010-05-25T23:53:48:760</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T23:53:48:800</value>
            <value>2010-05-25T23:53:50:120</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T23:53:50:160</value>
            <value>2010-05-25T23:53:55:280</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-25T23:53:55:320</value>
            <value>2010-05-25T23:59:43:040</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-25T23:59:43:080</value>
            <value>2010-05-25T23:59:44:320</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-25T23:59:44:400</value>
            <value>2010-05-26T00:03:00:720</value>
            <value>biken</value>
         </instance>
         <instance>
            <value>2010-05-26T00:03:00:760</value>
            <value>2010-05-26T00:03:00:800</value>
            <value>Joggen</value>
         </instance>
         <instance>
            <value>2010-05-26T00:03:00:840</value>
            <value>2010-05-26T00:03:06:800</value>
            <value>spazieren</value>
         </instance>
         <instance>
            <value>2010-05-26T00:03:06:840</value>
            <value>2010-05-26T00:07:29:480</value>
            <value>biken</value>
         </instance>
         <instance>